#the docker compose file version
version: '3.8'
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  # service 1 name
  reactjs-playground-dev:
    # service 1 container name
    working_dir: /reactjs-playground
    container_name: app-dev
    build:
      # the context (working directory) is the current directory
      # change this to the directory containing the dockerfile if in a different place
      context: ..
      # the dockerfile to be run
      dockerfile: ./docker/dockerfile-dev
    # map the exposed port from the underlying service to a port exposed to the outside
    # in this case  map port 3000 exposed by create react app to also 3000
    # to be used to access the container from the outside
    ports:
      - '3000:3001'
    # the mounted volumes (folders which are outside docker but being used by docker)
    volumes:
      - './:/reactjs-playground'
      - '/reactjs-playground/node_modules'
    # set the environment to development
    environment:
      - NODE_ENV=development
