### Build environment
FROM node:alpine as build

WORKDIR /reactjs-playground

COPY . /reactjs-playground

ENV PATH /reactjs-playground/node_modules/.bin:$PATH

RUN npm install

RUN npm run build


### Production environment
FROM nginx:alpine

COPY --from=build /reactjs-playground/build /usr/share/nginx/html

# remove default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# replace with custom one
COPY nginx/nginx.conf /etc/nginx/conf.d

# --------- /only for those using react router ----------
# expose port 80 to the outer world
EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]